//! The registry's public surface, checked in as a reviewable text file.
//!
//! Every operation, its route, its CLI invocation, its MCP tool, who may call
//! it, and what it requires — one line each, sorted. A reviewer reads the diff
//! of `surface.txt` rather than 130 declarations, and any change to what Loom
//! exposes shows up there whether or not the author mentioned it.
//!
//! Regenerate deliberately: `UPDATE_SURFACE=1 cargo test -p weaver-api --test surface`

use std::fmt::Write as _;

fn render() -> String {
    let mut out = String::new();
    out.push_str("# Loom operation surface — generated by tests/surface.rs, do not edit.\n");
    out.push_str("# id | method path | actor | risk | cli | mcp | grants\n\n");

    let mut lines: Vec<String> = weaver_api::operations::operations()
        .map(|operation| {
            let mut line = String::new();
            write!(
                &mut line,
                "{:<34} {} {:<44} {:<7} {:<9}",
                operation.id,
                operation.method(),
                operation.path(),
                operation.actor.as_str(),
                operation.risk.as_str(),
            )
            .expect("write to string");
            write!(
                &mut line,
                " cli={:<28}",
                operation
                    .cli
                    .map(|cli| cli.invocation())
                    .unwrap_or_else(|| "-".to_string())
            )
            .expect("write to string");
            write!(
                &mut line,
                " mcp={:<28}",
                operation
                    .mcp
                    .map(|mcp| format!("{}::{}", mcp.server, mcp.tool))
                    .unwrap_or_else(|| "-".to_string())
            )
            .expect("write to string");
            write!(
                &mut line,
                " grants=[{}]",
                operation.grants.join(",")
            )
            .expect("write to string");
            line
        })
        .collect();
    lines.sort();
    for line in lines {
        out.push_str(&line);
        out.push('\n');
    }
    out
}

#[test]
fn surface_matches_the_checked_in_snapshot() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/surface.txt");
    let current = render();
    if std::env::var("UPDATE_SURFACE").is_ok() {
        std::fs::write(&path, &current).expect("write surface snapshot");
        return;
    }
    let expected = std::fs::read_to_string(&path).unwrap_or_default();
    assert_eq!(
        current.trim_end(),
        expected.trim_end(),
        "the operation surface changed.\n\n\
         If that was deliberate, regenerate and review the diff:\n  \
         UPDATE_SURFACE=1 cargo test -p weaver-api --test surface\n"
    );
}
